plugins {
    id 'com.android.application'
}

android {
    namespace 'uz.pult.app'
    compileSdk 34

    defaultConfig {
        applicationId "uz.pult.app"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    // Give the built file a readable name
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "Pult-${variant.name}-${variant.versionName}.apk"
        }
    }
}
